# Generated by Django 3.2.18 on 2025-04-05 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesapp', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
